### ISSUE TITLE
This is a test. Can i add this? 

### ISSUE THREAD

**Issue by juliagtzp** [massgov/support-test#1]
OMG

**Comment by juliagtz89** [comment]
As a person that is not in this repo as a collaborator, I can comment.

**Comment by juliagtz89** [comment]
I cannot close an issue that i didn't open.

**Comment by juliagtzp** [comment]
However, as the person that created the issue, yes I can close it.

**Comment by juliagtzp** [comment]
that is not necessarily a bad thing.

**Comment by juliagtz89** [comment]
As a person (any person I believe) I can still comment on closed tickets.

**Comment by juliagtzp** [comment]
As the person that created the isue, i can reopen it.

**Comment by juliagutierrez** [comment]
As an admin. i can close it and lock the convo.
