### ISSUE TITLE
This is kinda confusing to get to

### ISSUE THREAD

**Issue by FriendlyHelper555** [massgov/support-test#8]
There is so much of this GitHub website that seems to have nothing to do with me.

I've "starred" something. Is that like "bookmarking" it? Is that the best way?

I'll bookmark this "New issue" page in my browser!

**Comment by kellyalb** [comment]
Hi @FriendlyHelper555, I've reproduced your issue and am putting it on deck for continued support. We will followup soon.

**Comment by kellyalb** [comment]
We will control this UX by linking you straight to where you need to be, ie "New Issue," but you are more than welcome to bookmark URL to get yourself here on your own anytime.

**Comment by FriendlyHelper555** [comment]
I'd like to re-open this but I can't...

**Comment by FriendlyHelper555** [comment]
I have new information that shows this is not resolved...

**Comment by FriendlyHelper555** [comment]
Re-open?
